INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1, 'AWS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1, 'Alexa');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1, 'Amazon Web Services');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1, 'Audible');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1, 'Kindle');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1, 'MGM');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1, 'Prime Video');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1, 'Ring');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1, 'Twitch');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1, 'Whole Foods');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2, 'Sam''s Club');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (3, 'Optum');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (3, 'United Healthcare');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (4, 'Beats');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (4, 'Shazam');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (4, 'iCloud');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (5, 'DeepMind');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (5, 'Fitbit');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (5, 'GCP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (5, 'Google');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (5, 'Google Cloud');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (5, 'Waymo');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (5, 'Waze');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (5, 'YouTube');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (9, 'Aetna');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (9, 'CVS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (11, 'Duracell');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (11, 'Fruit of the Loom');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (11, 'GEICO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (11, 'NetJets');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (11, 'See''s Candies');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (12, 'Esso');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (12, 'Exxon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (12, 'Mobil');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (13, 'AmerisourceBergen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (14, 'Activision Blizzard');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (14, 'Azure');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (14, 'Bing');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (14, 'GitHub');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (14, 'LinkedIn');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (14, 'Nuance');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (14, 'Skype');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (14, 'Xbox');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (18, 'Anthem');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (19, 'Lincoln');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (20, 'Facebook');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (20, 'Instagram');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (20, 'Oculus');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (20, 'WhatsApp');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (22, 'Cadillac');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (22, 'Chevrolet');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (22, 'GM');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (22, 'GMC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (25, 'Chase');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (25, 'JPMorgan');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (27, 'Boots');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (29, 'Fred Meyer');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (29, 'Harris Teeter');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (29, 'Ralphs');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (29, 'Smith''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (30, 'Fios');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (31, 'Marathon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (36, 'NBC Universal');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (36, 'Sky');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (36, 'Xfinity');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (42, 'BofA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (42, 'Merrill Lynch');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (44, 'ABC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (44, 'ESPN');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (44, 'Hulu');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (44, 'Lucasfilm');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (44, 'Marvel');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (44, 'National Geographic');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (44, 'Pixar');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (45, 'Doritos');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (45, 'Frito-Lay');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (45, 'Gatorade');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (45, 'Lay''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (45, 'Mountain Dew');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (45, 'Pepsi');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (45, 'Quaker');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (45, 'Tropicana');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (46, 'J&J');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (49, 'Pratt & Whitney');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (49, 'Raytheon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Advil');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Always');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Bounty');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Braun');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Charmin');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Crest');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Downy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Febreze');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Gillette');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Head & Shoulders');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Iams');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Olay');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Old Spice');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Oral-B');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'P&G');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Pampers');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Pantene');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Pringles');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Swiffer');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Tampax');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Tide');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (51, 'Vicks');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (53, 'ADM');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (55, 'Acme');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (55, 'Jewel-Osco');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (55, 'Safeway');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (55, 'Shaw''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (55, 'Vons');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (57, 'Sunoco');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (59, 'Citibank');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (64, 'Esurance');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (66, 'AmEx');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (80, 'HomeGoods');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (80, 'Marshalls');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (80, 'Sierra Trading Post');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (80, 'TJ Maxx');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (87, 'Spectrum');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (99, 'Coke');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (99, 'Dasani');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (99, 'Fanta');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (99, 'Minute Maid');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (99, 'Monster');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (99, 'Powerade');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (99, 'Sprite');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (101, 'Converse');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (101, 'Hurley');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (101, 'Jordan');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (102, 'John Deere');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (103, 'Snapdragon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (104, 'GE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (106, 'Fisher Scientific');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (111, 'Geek Squad');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (116, 'MuleSoft');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (116, 'Slack');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (116, 'Tableau');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (118, 'Marlboro');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (125, 'Cadbury');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (125, 'Nabisco');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (125, 'Oreo');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (125, 'Trident');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (127, 'Crucial');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (131, 'HP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (134, 'Florida Blue');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (135, 'Venmo');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (136, 'AMD');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (150, 'Paramount Pictures');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (150, 'Paramount+');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (156, 'LUV');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (159, 'Sinclair');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (160, 'Oxy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (161, 'Marsh');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (161, 'Mercer');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (164, 'Agoda');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (164, 'Kayak');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (164, 'OpenTable');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (164, 'Priceline');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (167, 'Capri Sun');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (167, 'Heinz');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (167, 'Jell-O');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (167, 'Kool-Aid');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (167, 'Kraft');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (167, 'Lunchables');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (167, 'Maxwell House');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (167, 'Oscar Mayer');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (167, 'Philadelphia');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (167, 'Velveeta');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (168, 'Renaissance');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (168, 'Ritz-Carlton');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (168, 'Sheraton');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (168, 'St. Regis');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (168, 'The Luxury Collection');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (168, 'W Hotels');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (168, 'Westin');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (170, 'Post-it');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (170, 'Scotch');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (173, 'Ticketmaster');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (179, 'NAPA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (180, 'Acrobat');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (180, 'Illustrator');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (180, 'Photoshop');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (190, 'Kidde');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (191, 'DD''s Discounts');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (191, 'Ross Dress for Less');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (205, 'Ajax');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (205, 'Colgate');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (205, 'Fabuloso');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (205, 'Irish Spring');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (205, 'Lady Speed Stick');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (205, 'Palmolive');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (205, 'Softsoap');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (205, 'Tom''s of Maine');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (207, 'Andrex');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (207, 'Depend');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (207, 'GoodNites');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (207, 'Huggies');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (207, 'Kleenex');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (207, 'Kotex');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (207, 'Poise');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (207, 'Scott');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (209, 'Credit Karma');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (209, 'MailChimp');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (209, 'QuickBooks');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (209, 'TurboTax');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (212, 'Betty Crocker');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (212, 'Cheerios');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (212, 'Chex');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (212, 'Fiber One');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (212, 'Green Giant');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (212, 'Häagen-Dazs');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (212, 'Lucky Charms');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (212, 'Old El Paso');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (212, 'Pillsbury');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (212, 'Progresso');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (212, 'Yoplait');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (213, 'Family Dollar');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (235, 'Aria');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (235, 'Bellagio');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (235, 'Cosmopolitan');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (235, 'Excalibur');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (235, 'Luxor');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (235, 'Mandalay Bay');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (235, 'Mirage');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (235, 'New York-New York');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (235, 'Park MGM');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (241, 'Con Ed');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (250, '7UP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (250, 'A&W');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (250, 'Canada Dry');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (250, 'Dr Pepper');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (250, 'Green Mountain Coffee');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (250, 'Keurig');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (250, 'Mott''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (250, 'Snapple');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (252, 'BBDO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (252, 'DDB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (252, 'Grey');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (252, 'TBWA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (256, 'ITW');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (259, 'Principal');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (261, 'Glidden');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (264, 'Amana');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (264, 'Jenn-Air');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (264, 'KitchenAid');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (264, 'Maytag');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (267, 'Athleta');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (267, 'Banana Republic');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (267, 'Old Navy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (268, 'DISH');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (270, 'Black & Decker');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (270, 'Craftsman');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (270, 'DeWalt');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (270, 'Stanley');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (273, 'Listerine');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (273, 'Nicorette');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (273, 'Tylenol');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (274, 'Platts');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (274, 'Standard & Poor''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (275, 'Gorilla Glass');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (281, 'Aramis');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (281, 'Aveda');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (281, 'Bobbi Brown');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (281, 'Clinique');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (281, 'Darphin');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (281, 'Jo Malone');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (281, 'La Mer');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (281, 'MAC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (281, 'Origins');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (281, 'Smashbox');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (281, 'Tom Ford Beauty');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (282, 'Hotels.com');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (282, 'Orbitz');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (282, 'Travelocity');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (282, 'VRBO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (283, 'Otis');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (286, 'Beechcraft');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (286, 'Bell');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (286, 'Cessna');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (289, 'Alaska Airlines');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (289, 'Horizon Air');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (289, 'Virgin America');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (293, 'FNF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (298, 'SDG&E');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (298, 'SoCalGas');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (300, 'U.S. Steel');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (313, 'CenturyLink');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (321, 'Cheddar''s Scratch Kitchen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (321, 'LongHorn Steakhouse');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (321, 'Olive Garden');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (321, 'Red Lobster');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (321, 'Yard House');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (322, 'The Palazzo');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (322, 'The Venetian');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (323, 'AllModern');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (323, 'Joss & Main');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (326, 'Jennie-O');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (326, 'Skippy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (326, 'Spam');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (341, 'Avis');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (341, 'Budget');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (346, 'KFC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (346, 'Pizza Hut');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (346, 'Taco Bell');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (347, 'Kisses');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (347, 'Reese''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (347, 'Sour Patch Kids');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (347, 'Twizzlers');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (349, 'Birds Eye');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (349, 'Hunt''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (349, 'Marie Callender''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (349, 'Reddi-wip');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (349, 'Slim Jim');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (350, 'Caesars Palace');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (350, 'Flamingo');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (350, 'Harrah''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (350, 'The LINQ');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (353, 'Blue Moon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (353, 'Coors');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (353, 'Molson');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (356, 'ADI');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (357, 'Canopy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (357, 'Conrad');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (357, 'DoubleTree');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (357, 'Hampton');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (357, 'Hilton Garden Inn');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (357, 'Homewood Suites');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (357, 'Waldorf Astoria');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (360, 'IPG');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (360, 'McCann');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (361, 'Daltile');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (362, 'Kijiji');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (362, 'StubHub');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (363, 'NVHomes');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (363, 'Ryan Homes');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (365, 'Ally Bank');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (365, 'GMAC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (367, 'FIS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (368, 'AMT');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (370, 'JLG');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (371, 'Pace');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (371, 'Swanson');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (371, 'V8');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (372, 'HGST');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (372, 'SanDisk');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (372, 'WD');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (373, 'TSYS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (375, 'Fendt');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (375, 'Massey Ferguson');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (375, 'Valtra');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (376, 'Spicer');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (378, 'Airstream');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (378, 'Heartland');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (378, 'Jayco');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (378, 'Monaco');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (380, 'ICE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (380, 'NASDAQ');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (380, 'NYSE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (385, 'Corona');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (385, 'Pacifico');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (385, 'Robert Mondavi');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (386, 'da Vinci');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (394, 'Pep Boys');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (405, 'Arrow');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (405, 'Calvin Klein');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (405, 'Izod');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (405, 'Tommy Hilfiger');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (405, 'Van Heusen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (408, 'Avery');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (409, 'Franklin Templeton');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (410, 'Crisco');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (410, 'Folgers');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (410, 'Jif');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (415, 'Pandora');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (418, 'Barron''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (418, 'Dow Jones');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (418, 'The Times');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (418, 'The Wall Street Journal');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (421, 'Allen-Bradley');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (422, 'Consumers Energy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (427, 'KFC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (427, 'Pizza Hut');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (427, 'Taco Bell');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (427, 'The Habit Burger Grill');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (429, 'Biomet');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (429, 'Zimmer');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (431, 'Champs Sports');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (431, 'WSS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (432, 'Monster');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (436, 'Pottery Barn');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (436, 'Pottery Barn Kids');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (436, 'Pottery Barn Teen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (436, 'Williams-Sonoma Home');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (438, 'Regions Bank');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (443, 'Behr');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (443, 'Brizo');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (443, 'Delta');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (443, 'Hansgrohe');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (443, 'Kraftmaid');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (443, 'Merillat');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (443, 'Peerless');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (446, 'IMG');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (446, 'Roc Nation');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (446, 'UFC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (446, 'WME');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (446, 'WWE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (448, 'Citizens Bank');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (450, 'BioWare');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (450, 'EA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (450, 'Maxis');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (450, 'PopCap Games');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (450, 'Respawn Entertainment');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (451, 'Calphalon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (451, 'Contigo');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (451, 'Eastpak');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (451, 'Elmer''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (451, 'Graco');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (451, 'Oster');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (451, 'Paper Mate');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (451, 'Rubbermaid');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (451, 'Sharpie');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (454, 'AmeriHealth');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (454, 'Optum');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (454, 'Oxford');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (454, 'UnitedHealthcare');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (456, 'Express Scripts');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (456, 'HealthSpring');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (457, 'Citi');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (457, 'Citibank');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (458, 'Facebook');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (458, 'Instagram');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (458, 'Threads');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (458, 'WhatsApp');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (459, 'Boots');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (459, 'Duane Reade');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (459, 'Walgreens');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (460, 'Fios');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (461, 'Goldman Sachs');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (464, 'Delta');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (465, 'United');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (465, 'United Airlines');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (466, 'Performance Food');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (466, 'Reinhart');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (467, 'American');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (467, 'American Airlines');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (469, 'Cisco Systems');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (474, 'MassMutual');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (475, 'U.S. Bank');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (476, 'Bank of New York Mellon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (477, 'Discovery');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (477, 'HBO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (477, 'Max');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (477, 'Warner Bros.');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (480, 'L&M');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (480, 'Marlboro');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (483, 'Cadbury');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (483, 'Halls');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (483, 'Oreo');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (483, 'Sour Patch Kids');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (483, 'Toblerone');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (483, 'Trident');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (484, 'Trammell Crow');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (485, 'PNC Bank');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (486, 'Florida Blue');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (487, 'Braintree');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (487, 'Venmo');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (490, 'HPE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (491, 'Kohlberg Kravis Roberts');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (492, 'Ferguson Plumbing');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (493, 'CBS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (493, 'Comedy Central');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (493, 'MTV');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (493, 'Nickelodeon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (493, 'Paramount');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (494, 'American International Group');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (495, 'Alabama Power');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (495, 'Georgia Power');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (496, 'The Hartford');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (497, 'Afterpay');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (497, 'Cash App');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (497, 'Square');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (499, 'Agoda');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (499, 'Booking.com');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (499, 'Kayak');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (499, 'Priceline');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (501, 'RGA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (502, 'AmFam');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (503, 'Copenhagen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (503, 'Marlboro');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (503, 'Nat Sherman');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (503, 'Philip Morris USA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (503, 'Skoal');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (506, 'ADP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (508, 'Pulte Homes');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (509, 'Experis');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (509, 'Manpower');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (512, 'Grainger');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (517, 'Guardian');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (518, 'Edward Jones');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (521, 'BBDO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (521, 'DDB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (521, 'Ogilvy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (522, 'Bobbi Brown');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (522, 'Clinique');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (522, 'La Mer');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (522, 'MAC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (522, 'Origins');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (524, 'First Citizens Bank');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (529, 'Expedia');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (529, 'Hotels.com');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (529, 'Hotwire');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (529, 'Orbitz');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (529, 'VRBO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (532, 'Fifth Third Bank');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (539, 'LPL Financial');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (540, 'Citizens Bank');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (544, 'Avis');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (544, 'Budget');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (544, 'Zipcar');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (545, 'Alaska Airlines');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (546, 'Coors');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (546, 'Molson');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (548, 'KFC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (548, 'Pizza Hut');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (548, 'Taco Bell');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (549, 'Conrad');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (549, 'DoubleTree');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (549, 'Hampton');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (549, 'Hilton');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (549, 'Waldorf Astoria');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (550, 'Thrivent');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (552, 'Golin');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (552, 'McCann');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (552, 'Weber Shandwick');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (559, 'Dickies');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (559, 'Eastpak');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (559, 'The North Face');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (559, 'Timberland');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (559, 'Vans');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (563, 'Zulily');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (567, 'KeyBank');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (569, 'Optimum');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (569, 'Suddenlink');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (575, 'Great American');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (582, 'Bob Evans');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (585, 'IMG');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (585, 'UFC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (585, 'WME');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (586, 'SAIC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (591, 'Audi');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (591, 'Bentley');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (591, 'Bugatti');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (591, 'Ducati');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (591, 'Lamborghini');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (591, 'Porsche');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (591, 'SEAT');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (591, 'Skoda');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (592, 'Pennzoil');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (595, 'Amoco');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (596, 'Abarth');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (596, 'Alfa Romeo');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (596, 'Citroën');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (596, 'Fiat');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (596, 'Jeep');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (596, 'Lancia');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (596, 'Opel');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (596, 'Peugeot');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (596, 'Ram');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (596, 'Vauxhall');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (597, 'Mini');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (597, 'Rolls-Royce');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (598, 'AMG');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (598, 'Maybach');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (598, 'Smart');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (601, 'Arval');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (601, 'BNP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (601, 'Paribas');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (603, 'T-Mobile');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (603, 'Telekom');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (604, 'DEA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (605, 'PIMCO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (607, 'Statol');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (608, 'Auntie Anne''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (608, 'Dreyer''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (608, 'Häagen-Dazs');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (608, 'KitKat');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (608, 'Maggi');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (608, 'Nescafé');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (608, 'Nespresso');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (608, 'Perrier');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (608, 'Poland Spring');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (608, 'Purina');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (608, 'S.Pellegrino');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (609, 'Auntie Anne''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (609, 'Dreyer''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (609, 'Häagen-Dazs');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (609, 'KitKat');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (609, 'Maggi');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (609, 'Nescafé');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (609, 'Nespresso');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (609, 'Perrier');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (609, 'Poland Spring');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (609, 'Purina');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (609, 'S.Pellegrino');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (610, 'Endesa');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (613, 'Gazprom Neft');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (614, 'BSH');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (615, 'Albert Heijn');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (615, 'Delhaize');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (615, 'Food Lion');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (615, 'Stop & Shop');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (616, 'Amundi');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (616, 'LCL');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (617, 'Amundi');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (617, 'LCL');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (620, 'Penny');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (622, 'GDF Suez');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (626, 'Osram');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (632, 'Arcelor');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (632, 'Mittal');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (633, 'Genentech');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (635, 'Bank of Scotland');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (635, 'HBOS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (636, 'DB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (638, 'HUL');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (639, 'Barclaycard');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (641, 'SBER');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (646, 'Anheuser-Busch');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (646, 'Beck''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (646, 'Budweiser');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (646, 'Corona');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (646, 'Stella Artois');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (648, 'Dacia');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (653, 'DB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (657, 'Aspirin');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (658, 'Maersk Line');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (664, 'CNH Industrial');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (664, 'Ferrari');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (664, 'Stellantis');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (668, 'IKEA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Celine Beauty');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'CeraVe');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Essie');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Garnier');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Giorgio Armani Beauty');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'IT Cosmetics');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Kiehl''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'La Roche-Posay');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Lancôme');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Maybelline');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'NYX');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Pureology');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Ralph Lauren Beauty');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Real Techniques');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Redken');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'SkinCeuticals');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Urban Decay');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Valentino Beauty');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Vichy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (673, 'Yves Saint Laurent Beauty');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (675, 'Movistar');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (681, 'LH');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (683, 'Bershka');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (683, 'Massimo Dutti');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (683, 'Oysho');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (683, 'Pull & Bear');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (683, 'Stradivarius');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (683, 'Zara');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (686, 'Affligem');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (686, 'Amstel');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (686, 'Cruzcampo');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (686, 'Desperados');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (686, 'Lagunitas');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (686, 'Paulaner');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (686, 'Red Stripe');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (686, 'Sol');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (686, 'Strongbow');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (686, 'Tiger');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'A. Lange & Söhne');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'Bally');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'Baume & Mercier');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'Cartier');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'Chloe');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'Dunhill');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'IWC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'Jaeger-LeCoultre');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'Montblanc');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'Officine Panerai');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'Piaget');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'Roger Dubuis');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'Vacheron Constantin');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (695, 'Van Cleef & Arpels');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (700, 'EDF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (702, 'Albert Heijn');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (702, 'Delhaize');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (702, 'Pingo Doce');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (704, 'BIPA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (704, 'Penny');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (704, 'Toom');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (711, 'Fresenius Kabi');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (711, 'Fresenius Medical Care');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (712, 'Hannover Rück');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (722, 'AutoScout24');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (729, 'DHL');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (729, 'Postbank');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (732, 'ERGO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (732, 'Munich Re');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (733, 'CCM');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (733, 'TaylorMade');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (735, 'Aleve');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (735, 'Alka-Seltzer');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (735, 'Canesten');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (736, 'Eucerin');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (736, 'Hansaplast');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (736, 'Labello');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (736, 'Nivea');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (736, 'Tesa');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (737, 'Mini');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (737, 'Rolls-Royce');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (739, 'Comdirect');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (741, 'Freightliner');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (741, 'Western Star');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (742, 'DWS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (743, 'Eurex');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (744, 'Magenta');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (744, 'T-Mobile');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (748, 'Loctite');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (748, 'Persil');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (748, 'Pritt');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (748, 'Schwarzkopf');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (760, 'Alexander McQueen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (760, 'Balenciaga');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (760, 'Bottega Veneta');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (760, 'Boucheron');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (760, 'Gucci');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (760, 'Pomellato');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (760, 'Saint Laurent');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (762, 'Berluti');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (762, 'Celine');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (762, 'Dior');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (762, 'Dom Pérignon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (762, 'Fendi');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (762, 'Givenchy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (762, 'Hennessy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (762, 'Loewe');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (762, 'Loro Piana');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (762, 'Louis Vuitton');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (762, 'Moët & Chandon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (764, 'Absolut');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (764, 'Chivas Regal');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (764, 'Glenmorangie');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (764, 'Jameson');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (764, 'Laphroaig');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (764, 'Martell');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (764, 'Pernod');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (764, 'Ricard');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (765, 'Razorfish');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (765, 'Starcom');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (765, 'Zenith');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (768, 'SocGen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (772, 'Canal+');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (772, 'Universal Music Group');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (781, 'Fairmont');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (781, 'Ibis');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (781, 'Mercure');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (781, 'Novotel');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (781, 'Pullman');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (781, 'Raffles');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (781, 'Sofitel');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (786, 'Bouygues Telecom');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (786, 'TF1');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (790, 'Saint-Gobain');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (792, 'Actimel');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (792, 'Activia');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (792, 'Evian');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (793, 'CATIA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (793, 'SOLIDWORKS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (795, 'GDF Suez');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (796, 'Essilor');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (796, 'Luxottica');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (796, 'Oakley');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (796, 'Oliver Peoples');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (796, 'Persol');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (796, 'Ray-Ban');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (799, 'Garnier');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (799, 'Giorgio Armani Beauty');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (799, 'Lancôme');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (799, 'Maybelline');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (799, 'Ralph Lauren Beauty');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (799, 'Urban Decay');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (799, 'Yves Saint Laurent Beauty');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (802, 'Admiral');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (807, 'Sunbelt Rentals');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (808, 'ABF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (808, 'Argos');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (808, 'Dunelm');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (808, 'Primark');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (811, 'BAE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (812, 'Barratt');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (812, 'Redrow');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (815, 'BAT');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (815, 'Camel');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (815, 'Dunhill');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (815, 'Kent');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (815, 'L&M');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (815, 'Lucky Strike');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (815, 'Newport');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (815, 'Pall Mall');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (815, 'Rothmans');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (817, 'BT');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (817, 'EE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (817, 'Plusnet');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (819, 'Bord Gáis');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (819, 'British Gas');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (824, 'Baileys');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (824, 'Barnabus');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (824, 'Captain Morgan');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (824, 'Ciroc');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (824, 'Don Julio');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (824, 'Guinness');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (824, 'Johnnie Walker');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (824, 'Ketel One');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (824, 'Oppo');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (824, 'Smirnoff');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (824, 'Tanqueray');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (828, 'Coral');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (828, 'Ladbrokes');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (828, 'PartyPoker');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (828, 'PokerStars');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (828, 'bwin');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (831, 'Warhammer');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (832, 'GlaxoSmithKline');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (833, 'Advil');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (833, 'Panadol');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (833, 'Sensodyne');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (835, 'HL');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (836, 'Hikma');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (840, 'Davidoff');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (840, 'Rizla');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (842, 'Crowne Plaza');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (842, 'Holiday Inn');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (842, 'IHG');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (842, 'InterContinental');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (843, 'ICG');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (845, 'JD');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (846, 'B&Q');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (846, 'Brico Dépôt');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (846, 'Castorama');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (846, 'Screwfix');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (847, 'Landsec');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (848, 'L&G');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (849, 'LSE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (849, 'LSEG');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (852, 'M&S');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (856, 'RBS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (858, 'Financial Times');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (858, 'The Economist');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (862, 'Air Wick');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (862, 'Dettol');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (862, 'Durex');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (862, 'Finish');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (862, 'Lysol');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (862, 'Nurofen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (863, 'Elsevier');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (863, 'LexisNexis');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (882, 'Premier Inn');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (882, 'Travelodge');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (883, 'J. Walter Thompson');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (883, 'Ogilvy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (894, 'COS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (904, 'UPM');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (908, 'AEG');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (908, 'Zanussi');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (909, 'Yale');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (916, 'OP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (927, 'Leica Geosystems');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (932, 'Maquet');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (937, 'Panalpina');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (946, 'Oticon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (946, 'ReSound');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (949, 'Jabra');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (952, 'DONG Energy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (953, 'DONG Energy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (959, 'Bernafon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (959, 'Oticon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (959, 'Sonic Innovations');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (962, 'Statoil');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (963, 'Maersk');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (963, 'Maersk Line');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (964, 'Polestar');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (972, '& Other Stories');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (972, 'COS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (972, 'Monki');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (972, 'Weekday');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (976, 'Baltika');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (976, 'Kronenbourg');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (976, 'Tuborg');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (977, 'Libero');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (977, 'Tena');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (977, 'Tork');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (977, 'Viva');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (978, 'AZ');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (979, 'Yale');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (994, 'Hiab');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (994, 'Kalmar');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (996, 'EVRY');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (996, 'Tieto');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (998, 'Marine Harvest');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1007, 'AIT');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1007, 'IVT');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1014, 'Hemköp');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1014, 'Willys');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1017, 'EC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1019, 'EP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1019, 'Europarl');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1020, 'ECB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1021, 'EIB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1022, 'ESA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1029, 'WEF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1030, 'Treasury');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1034, 'MoD');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1039, 'BoE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1040, 'FCA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1045, 'CPS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1046, 'NCA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1049, 'RN');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1050, 'RAF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1051, 'TfL');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1053, 'National Highways');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1055, 'UKHSA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1070, 'THW');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1125, 'UN');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1127, 'IMF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1129, 'WTO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1131, 'WHO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1133, 'IEA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1135, 'IAEA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1139, 'Doctors Without Borders');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1139, 'MSF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1157, 'European Court of Justice');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1158, 'ECA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1159, 'EESC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1160, 'CoR');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1162, 'EEAS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1163, 'EMA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1164, 'EFSA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1165, 'EASA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1166, 'EMSA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1167, 'ERA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1168, 'ECHA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1169, 'EEA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1170, 'ECDC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1171, 'EFCA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1172, 'ENISA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1173, 'EBA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1174, 'EIOPA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1175, 'ESMA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1176, 'SRB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1177, 'Europol');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1178, 'Eurojust');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1179, 'EUAA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1180, 'Frontex');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1181, 'FRA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1182, 'EIGE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1183, 'EMCDDA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1184, 'CEPOL');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1185, 'eu-LISA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1186, 'EPPO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1187, 'EDA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1188, 'SatCen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1189, 'EUISS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1190, 'EUSPA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1191, 'EUIPO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1191, 'European Union Intellectual Property Office');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1192, 'CPVO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1193, 'Cedefop');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1194, 'ETF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1195, 'Eurofound');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1196, 'EU-OSHA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1197, 'ELA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1198, 'ACER');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1199, 'BEREC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1200, 'REA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1201, 'ERC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1201, 'European Research Council');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1205, 'DG AGRI');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1206, 'DG BUDG');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1207, 'DG CLIMA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1208, 'DG COMM');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1209, 'DG CONNECT');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1210, 'DG COMP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1211, 'DG ECFIN');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1212, 'DG EAC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1213, 'DG EMPL');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1214, 'DG ENER');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1215, 'DG ENV');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1216, 'DG SANTE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1217, 'DG GROW');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1218, 'DG INTPA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1219, 'DG JUST');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1220, 'DG MARE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1221, 'DG HOME');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1222, 'DG MOVE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1223, 'DG NEAR');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1224, 'DG RTD');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1225, 'DG TAXUD');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1226, 'DG TRADE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1227, 'DG DEFIS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1228, 'Eurostat');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1229, 'JRC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1231, 'FPI');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1233, 'BMF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1234, 'BMI');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1235, 'BMVg');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1236, 'AA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1238, 'BMAS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1240, 'BMJ');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1241, 'BMWK');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1242, 'BMG');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1243, 'BMEL');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1244, 'BMZ');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1245, 'BMWSB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1304, 'Holland');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1304, 'Netherlands');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1317, 'Belgium');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1326, 'Austria');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1333, 'Sweden');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1339, 'Denmark');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1354, 'Finland');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1361, 'Norway');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1373, 'Switzerland');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1381, 'Portugal');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1390, 'Greece');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1462, 'Slovakia');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1467, 'Slovenia');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1477, 'Lithuania');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1480, 'Latvia');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1484, 'Estonia');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1488, 'Luxembourg');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1497, 'Cyprus');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1504, 'Malta');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1519, 'Iceland');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1528, 'UK');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1529, 'FCDO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1530, 'DfE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1531, 'DHSC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1532, 'DWP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1533, 'DBT');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1534, 'DESNZ');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1535, 'DSIT');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1536, 'DEFRA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1537, 'DfT');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1538, 'DCMS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1539, 'DLUHC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1540, 'NIO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1543, 'AGO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1547, 'ECB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1548, 'CoR');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1549, 'EDPS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1550, 'ECCC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1551, 'EFSA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1552, 'EASO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1553, 'EASA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1554, 'Europol');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1555, 'CEPOL');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1556, 'ENISA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1557, 'EIGE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1558, 'EUIPO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1558, 'OHIM');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1559, 'ETF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1562, 'GSA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1563, 'ESA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1565, 'F4E');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1568, 'Quai d''Orsay');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1658, 'OLAF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1659, 'Eurostat');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1664, 'Lidl');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1704, 'Endesa');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1709, 'British Gas');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1756, 'Aftenposten');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1756, 'Bergens Tidende');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1756, 'Stavanger Aftenblad');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1756, 'VG');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1757, 'Dagens Nyheter');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1757, 'Expressen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1757, 'Göteborgs-Posten');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1757, 'Sydsvenskan');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1758, 'Helsingin Sanomat');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1758, 'Ilta-Sanomat');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1758, 'MTV3');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1758, 'Nelonen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1759, 'Hjemmet');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1759, 'Se og Hør');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1760, 'Femina');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1761, 'Bild');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1761, 'Die Welt');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1761, 'Politico');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1762, 'Penguin Random House');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1763, 'Kabel Eins');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1763, 'ProSieben');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1763, 'SAT.1');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1764, 'M6');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1765, 'OLX');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1765, 'Vinted');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1765, 'Wallapop');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1772, 'Webhallen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1776, 'Jack & Jones');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1776, 'Matinique');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1776, 'Minimum');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1776, 'Name It');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1776, 'Only');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1776, 'Pieces');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1776, 'Selected');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1776, 'Vero Moda');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1777, 'Calvin Klein');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1777, 'Speedo');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1777, 'Tommy Hilfiger');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1777, 'Van Heusen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1778, 'BOSS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1780, 'Alexander McQueen');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1780, 'Bottega Veneta');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1780, 'Boucheron');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1780, 'Brioni');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1780, 'Creed');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1780, 'Pomellato');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1780, 'Saint Laurent');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1784, 'Church''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1784, 'Miu Miu');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1790, 'D&G');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1798, 'B&O');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1800, 'Playskool');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1800, 'Wizards of the Coast');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1803, 'Gardena');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1803, 'Jonsered');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1803, 'Poulan');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1807, 'Kalmar');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1807, 'MacGregor');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1832, 'Bernafon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1832, 'Oticon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1833, 'Jabra');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1834, 'Phonak');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1834, 'Unitron');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1841, 'Libero');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1841, 'Tena');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1853, 'Castello');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1853, 'Lurisia');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1854, 'Tulip');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1855, 'Estrella');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1860, 'Hemtex');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1860, 'Rimi');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1861, 'Hemköp');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1861, 'Willys');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1862, 'Anttila');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1862, 'K-rauta');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1862, 'K-supermarket');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1863, 'S-Market');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1865, 'KIWI');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1865, 'Meny');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1867, 'Denner');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1867, 'M-budget');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1867, 'Manor');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1869, 'HORNBACH');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1869, 'Penny');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1871, 'Trader Joe''s');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1885, 'Harris + Hoole');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1896, 'Pret');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1901, 'Foodpanda');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1901, 'Talabat');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1901, 'Wolt');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1902, 'EveryPlate');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1902, 'Factor');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1902, 'Green Chef');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1904, 'Freia');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1904, 'Nidar');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1907, 'Marabou');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1912, 'Bird''s Eye');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1912, 'Findus');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1914, 'Parmalat');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1914, 'President');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1915, 'Actimel');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1915, 'Activia');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1915, 'Evian');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1915, 'Volvic');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1916, 'Campina');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1917, 'Campina');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1925, 'Tuborg');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1926, 'Amstel');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1927, 'Guinness');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1927, 'Johnnie Walker');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1928, 'Absolut');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1928, 'Chivas Regal');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1928, 'Jameson');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1929, 'Dom Pérignon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1929, 'Hennessy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1929, 'Moët & Chandon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1930, 'Dom Pérignon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1930, 'Hennessy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1930, 'Moët & Chandon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1933, 'Bombay Sapphire');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1933, 'Grey Goose');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1933, 'Martini');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1934, 'Skyy');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1934, 'Wild Turkey');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1943, 'Silja Line');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1948, 'Norwegian');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1956, 'Transavia');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1957, 'Austrian Airlines');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1957, 'Brussels Airlines');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1957, 'Eurowings');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1957, 'Swiss International');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1971, 'State Department');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1972, 'Treasury');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1973, 'DoD');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1974, 'DOJ');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1975, 'Interior');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1976, 'USDA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1977, 'Commerce');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1978, 'Labor');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1979, 'HHS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1980, 'HUD');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1981, 'DOT');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1982, 'DOE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1983, 'Education');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1984, 'VA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1985, 'DHS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1986, 'CIA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1987, 'NSA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1988, 'FBI');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1989, 'DEA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1990, 'ATF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1991, 'U.S. Marshals');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1992, 'Secret Service');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1993, 'CBP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1994, 'ICE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1995, 'TSA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1996, 'Coast Guard');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1997, 'DIA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1998, 'NGA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (1999, 'NRO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2000, 'ODNI');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2001, 'EPA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2002, 'NASA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2003, 'SSA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2004, 'FTC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2005, 'SEC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2006, 'FCC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2007, 'Fed');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2007, 'Federal Reserve');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2008, 'FDIC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2009, 'CFTC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2010, 'CFPB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2011, 'NLRB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2012, 'EEOC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2013, 'OSHA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2014, 'NRC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2015, 'SBA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2016, 'GSA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2017, 'OPM');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2018, 'NARA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2019, 'USPS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2020, 'NSF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2021, 'USAID');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2024, 'FEC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2025, 'CPSC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2026, 'FHFA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2029, 'TVA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2030, 'NTSB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2037, 'DOS');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2037, 'State Department');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2038, 'DoD');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2038, 'Pentagon');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2039, 'DOJ');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2040, 'DOE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2041, 'ED');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2043, 'KSA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2044, 'MOD');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2289, 'Itamaraty');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2396, 'MARN');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2402, 'MARN');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2404, 'MSPP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2413, 'MSPP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2422, 'SERNA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2434, 'SERNA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2440, 'SEGOB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2441, 'SEGOB');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2442, 'SEDENA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2443, 'SEMAR');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2444, 'SSPC');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2445, 'SHCP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2447, 'SEMARNAT');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2448, 'SENER');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2450, 'SADER');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2454, 'SEP');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2482, 'MINAM');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2571, 'Banco Central');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2572, 'CORFO');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2573, 'SERNAM');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2590, 'CAJA');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2709, 'Indian Railways');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2711, 'MeitY');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2754, 'SBV');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2756, 'DND');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2757, 'DSWD');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2758, 'DPWH');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2759, 'DILG');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2760, 'DOLE');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2761, 'DOF');
INSERT OR IGNORE INTO aliases (company_id, alias) VALUES (2762, 'DFA');
